apiVersion: v1
kind: Service
metadata:
  name: backend # Це ім'я буде використовувати фронтенд (Nginx)
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP # Бекенд поки що теж тільки для внутрішніх потреб