apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: todo-backend # Назва образу, який ми збирали всередині Minikube
        imagePullPolicy: Never # КАЖЕМО: Не шукай в інтернеті, бери локально!
        env:
        - name: DATABASE_URL
          # Зверніть увагу на @postgres — це ім'я сервісу бази даних
          value: "postgresql://postgres:mysecretpassword@postgres:5432/todo_db"
        ports:
        - containerPort: 8080