apiVersion: v1
kind: Service
metadata:
  name: postgres # Це ім'я стане DNS-адресою для бекенду
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP # База доступна тільки всередині кластера