apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1 # Нам потрібна лише одна копія бази
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
        - name: POSTGRES_DB
          value: "todo_db"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data # Куди всередині контейнера підключити диск
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc